package interfaces;

import classes.Calculadora;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andressa Atelli (10/2020)
 */
public class CalculadoraForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraForm
     */
    int operacao = 0;
    int virgula = 0; 
    double num1, num2, num;
    Calculadora calc = new Calculadora();
    
    public CalculadoraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonVirgula = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        lblExpressao = new javax.swing.JLabel();
        jButtonC = new javax.swing.JButton();
        jButtonInverso = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        txfConta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 300, 70, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 300, 70, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 300, 70, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 240, 70, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 240, 70, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(170, 240, 70, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 180, 70, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(90, 180, 70, 50);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(170, 180, 70, 50);

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0);
        jButton0.setBounds(90, 360, 70, 50);

        jButtonVirgula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVirgula.setText(",");
        jButtonVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVirgulaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVirgula);
        jButtonVirgula.setBounds(10, 360, 70, 50);

        jButtonIgual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIgual);
        jButtonIgual.setBounds(170, 360, 70, 50);

        btnSomar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSomar.setText("+");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar);
        btnSomar.setBounds(260, 360, 70, 50);

        jButtonSubtracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSubtracao.setText("_");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubtracao);
        jButtonSubtracao.setBounds(260, 300, 70, 50);

        jButtonMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMultiplicacao.setText("x");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiplicacao);
        jButtonMultiplicacao.setBounds(260, 240, 70, 50);

        jButtonDivisao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivisao);
        jButtonDivisao.setBounds(260, 180, 70, 50);

        lblExpressao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExpressao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblExpressao);
        lblExpressao.setBounds(70, 20, 260, 30);

        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonC.setText("c");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC);
        jButtonC.setBounds(259, 120, 70, 50);

        jButtonInverso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonInverso.setText("1/x");
        jButtonInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInversoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInverso);
        jButtonInverso.setBounds(170, 120, 70, 50);

        jButtonRaiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRaiz.setText("Raiz (x)");
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRaiz);
        jButtonRaiz.setBounds(10, 120, 150, 50);

        txfConta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfConta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfConta.setText("0");
        txfConta.setEnabled(false);
        txfConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfContaActionPerformed(evt);
            }
        });
        getContentPane().add(txfConta);
        txfConta.setBounds(10, 60, 320, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Calculadora feita por Andressa Atelli");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 0, 210, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (txfConta.getText().equals("0")){
            txfConta.setText("1");
        }
        else{
            txfConta.setText(txfConta.getText()+"1");
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("2");
        }
        else{
            txfConta.setText(txfConta.getText()+"2");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("3");
        }
        else{
            txfConta.setText(txfConta.getText()+"3");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("4");
        }
        else{
            txfConta.setText(txfConta.getText()+"4");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("5");
        }
        else{
            txfConta.setText(txfConta.getText()+"5");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("6");
        }
        else{
            txfConta.setText(txfConta.getText()+"6");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("7");
        }
        else{
            txfConta.setText(txfConta.getText()+"7");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("8");
        }
        else{
            txfConta.setText(txfConta.getText()+"8");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("9");
        }
        else{
            txfConta.setText(txfConta.getText()+"9");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        if (txfConta.getText().equals("0")){
            txfConta.setText("0");
            
        }
        else{
            txfConta.setText(txfConta.getText()+"0");
        }
    
    }//GEN-LAST:event_jButton0ActionPerformed

    private void txfContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfContaActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        txfConta.setText("0");
        virgula = 0;
        lblExpressao.setText("");
    
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVirgulaActionPerformed
         if (virgula == 0){
            if (txfConta.getText().equals("0")){
                txfConta.setText("0.");
                virgula = 1;
            }
            else{
                txfConta.setText(txfConta.getText()+".");
                virgula = 1;
            }
         }
    }//GEN-LAST:event_jButtonVirgulaActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        operacao = 1;
        num1 = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(num1+" + ");
        txfConta.setText("0");
        
    
    }//GEN-LAST:event_btnSomarActionPerformed

    
    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        num2 = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(lblExpressao.getText()+""+num2+" = ");
        if (operacao == 1){
            txfConta.setText(""+calc.somar(num1, num2));
        }
        else if (operacao == 2){
            txfConta.setText(""+calc.subtrair(num1, num2));
        }
        else if (operacao == 3){
            txfConta.setText(""+calc.multiplicar(num1, num2));
        }
        else if (operacao == 4){
            txfConta.setText(""+calc.dividir(num1, num2));
        }
         else if (operacao == 5){
            txfConta.setText(""+calc.calcularRaiz(num));
        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        operacao = 2;
        num1 = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(num1+" - ");
        txfConta.setText("0"); 
        
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInversoActionPerformed
        lblExpressao.setText("1/("+txfConta.getText()+") =");
        num1 = Double.parseDouble(txfConta.getText());
        num1 = Double.parseDouble(calc.calcularInverso(num1).replace(',', '.'));
        txfConta.setText(""+num1);   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInversoActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        operacao = 3;
        num1 = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(num1+" * ");
        txfConta.setText("0");      // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        operacao = 4;
        num1 = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(num1+" * ");
        txfConta.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        operacao = 5;
        num = Double.parseDouble(txfConta.getText());
        lblExpressao.setText(num+" Raiz ");
        txfConta.setText("0");   
    }//GEN-LAST:event_jButtonRaizActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonInverso;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExpressao;
    private javax.swing.JTextField txfConta;
    // End of variables declaration//GEN-END:variables
}
